puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Alex Parkinson"
puts "Carrie Christenson"
puts "Costas Sarris"
puts "Diego Romero"
puts "Ed Brown"
puts "Erik Brown"
puts "Gabe Arafa"
puts "Guido Fawkes"
puts "Jow Newman"
puts "Julian Veling"
puts "Kate Beavis"
puts "Kevin Lanzon"
puts "Louise Beh"
puts "Loris Fochesato"
puts "Margherita Serino"
puts "Meads Chalcroft"
puts "Paul Fitz"
puts "Phil Brockwell"
puts "Ptolemy Barnes"
puts "Riz Ali"
puts "Sanda Golcea"
puts "Sean Haughton"
puts "Sebastien Pires"
puts "Thomas Strothjohann"
puts "Tom Coakes"
puts "Tom Bratto"
puts "Vanessa Virgitti"
puts "Yannick Brunner"

print "Overall, we have "
print 28
puts " great students"